spring:
  config:
    import: "classpath:api-keys.yml"
  elasticsearch:
    rest:
      uris: ${instance}
      username: ${instanceUN}
      password: ${instancePW}
  data:
    elasticsearch:
      repositories:
        enabled: false




springdoc:
  packages-to-scan: com.clds.bottletalk
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8