spring:
  profiles:
    active: "local"
  config:
    import: "classpath:secrets.yml"

aws:
  access-key-cognito: ${aws-secret.access-key-cognito}
  secret-key-cognito: ${aws-secret.secret-key-cognito}
  cognito:
    userPoolId: ${aws-secret.cognito.userPoolId}
    region: ${aws-secret.cognito.region}


resource:
  origin: ${frontend.domain}


jasypt:
  encryptor:
    bean: "jasyptStringEncryptor"
    key: ${secret.jasypt.encryptor.key}

redis:
  baseUrl: ${secret.redis.baseUrl}