name: Build and Upload to S3

on:
  push:
    branches:
      - develop

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Create secrets.yml
      run: |
        echo "dev:" > spring/src/main/resources/secrets.yml
        echo "  host: ${{ secrets.DEV_HOST }}" >> spring/src/main/resources/secrets.yml
        echo "  port: ${{ secrets.DEV_PORT }}" >> spring/src/main/resources/secrets.yml
        echo "  scheme: ${{ secrets.DEV_SCHEME }}" >> spring/src/main/resources/secrets.yml
        echo "  username: ${{ secrets.DEV_USERNAME }}" >> spring/src/main/resources/secrets.yml
        echo "  password: ${{ secrets.DEV_PASSWORD }}" >> spring/src/main/resources/secrets.yml
        echo "  index-for-top5: ${{ secrets.DEV_INDEX_FOR_TOP5 }}" >> spring/src/main/resources/secrets.yml
        echo "  index-for-products: ${{ secrets.DEV_INDEX_FOR_PRODUCTS }}" >> spring/src/main/resources/secrets.yml

        echo "" >> spring/src/main/resources/secrets.yml
        echo "local:" >> spring/src/main/resources/secrets.yml
        echo "  host: ${{ secrets.LOCAL_HOST }}" >> spring/src/main/resources/secrets.yml
        echo "  port: ${{ secrets.LOCAL_PORT }}" >> spring/src/main/resources/secrets.yml
        echo "  scheme: ${{ secrets.LOCAL_SCHEME }}" >> spring/src/main/resources/secrets.yml
        echo "  username: ${{ secrets.LOCAL_USERNAME }}" >> spring/src/main/resources/secrets.yml
        echo "  password: ${{ secrets.LOCAL_PASSWORD }}" >> spring/src/main/resources/secrets.yml
        echo "  index-for-top5: ${{ secrets.LOCAL_INDEX_FOR_TOP5 }}" >> spring/src/main/resources/secrets.yml
        echo "  index-for-products: ${{ secrets.LOCAL_INDEX_FOR_PRODUCTS }}" >> spring/src/main/resources/secrets.yml

        echo "" >> spring/src/main/resources/secrets.yml
        echo "aws-secret:" >> spring/src/main/resources/secrets.yml
        echo "  access-key-cognito: ${{ secrets.AWS_ACCESS_KEY_COGNITO }}" >> spring/src/main/resources/secrets.yml
        echo "  secret-key-cognito: ${{ secrets.AWS_SECRET_KEY_COGNITO }}" >> spring/src/main/resources/secrets.yml
        echo "  cognito:" >> spring/src/main/resources/secrets.yml
        echo "    userPoolId: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}" >> spring/src/main/resources/secrets.yml
        echo "    region: ${{ secrets.AWS_COGNITO_REGION }}" >> spring/src/main/resources/secrets.yml

        echo "" >> spring/src/main/resources/secrets.yml
        echo "frontend:" >> spring/src/main/resources/secrets.yml
        echo "  domain: ${{ secrets.FRONTEND_DOMAIN }}" >> spring/src/main/resources/secrets.yml

        echo "" >> spring/src/main/resources/secrets.yml
        echo "secret:" >> spring/src/main/resources/secrets.yml
        echo "  jasypt:" >> spring/src/main/resources/secrets.yml
        echo "    encryptor:" >> spring/src/main/resources/secrets.yml
        echo "      key: ${{ secrets.JASYPT_ENCRYPTOR_KEY }}" >> spring/src/main/resources/secrets.yml
        echo "  redis:" >> spring/src/main/resources/secrets.yml
        echo "    baseUrl: ${{ secrets.REDIS_BASEURL }}" >> spring/src/main/resources/secrets.yml
    
    
    
    

    - name: Build with Gradle
      run: ./gradlew build -x test
      working-directory: spring

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION : ap-northeast-2
      run: |
        aws s3 cp spring/build/libs/spring-0.0.1-SNAPSHOT.jar s3://${{ secrets.AWS_S3_NAME }}/product-api/
